# Generated by Django 4.0.5 on 2022-06-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='prueba',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
